alias vim='nvim'
alias tmux='tmux -2'
alias sbrc='source ~/.bashrc'
alias szrc='source ~/.zshrc'

alias python='python3'
alias python2='\python'
alias pip='pip3'
alias pip2='\pip'

alias venv='virtualenv'
alias venva='source venv/bin/activate'

alias wget-agent='wget --user-agent="Mozilla/5.0"' # Get around 403 forbidden with wget
