#!/bin/zsh

if [[ -z "$PS1" ]]; then return; fi

source "$HOME/.config/bash/bash_common"

alias szrc="source ~/.zshrc"

# Initialize color expansion
# Use with $fg[green] or %{$fg[green]%}
autoload -Uz colors && colors

HISTFILE=~/.zsh_history
setopt appendhistory
setopt incappendhistory # Immediate append instead of on terminal exit
setopt histignorealldups
setopt sharehistory

# Disable autocomplete cycling through options with tab completion
setopt nomenucomplete
setopt noautomenu

# Terminal Prompt
PROMPT="%{$fg[green]%}%n@%m:%{$fg[blue]%}%~%{$reset_color%}$ "
# PROMPT="%n@%m:%~$ "

# Load completion
autoload -Uz compinit && compinit

# Add colors in completions
eval $(dircolors)
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}

bindkey '^_' undo # ctrl + _ : undo last tab completion
bindkey -v # vi mode
bindkey '^r' history-incremental-search-backward

bindkey  "^[[H"   beginning-of-line # home
bindkey  "^[[F"   end-of-line       # end

if has_cmd direnv; then
  eval "$(direnv hook zsh)"
fi
