#!/bin/zsh

if [[ -z "$PS1" ]]; then return; fi

source "$HOME/.config/bash/bash_common"

alias szrc="source ~/.zshrc"

# Initialize color expansion
# Use with $fg[green] or %{$fg[green]%}
autoload -Uz colors && colors

# history
HISTFILE="$XDG_DATA_HOME/zsh/history"
SAVEHIST=1000
setopt appendhistory
setopt incappendhistory # Immediate append instead of on terminal exit
setopt histignorealldups
setopt sharehistory

# Disable autocomplete cycling through options with tab completion
setopt nomenucomplete
setopt noautomenu

setopt interactivecomments # allow hashes to comment-out directly in cmd line

# Terminal Prompt
PROMPT="%{$fg[green]%}%n@%m:%{$fg[blue]%}%~%{$reset_color%}$ "

# Load completion
autoload -Uz compinit && compinit -d "$XDG_DATA_HOME/zsh/compinit_dump"

# Add colors in completions
eval $(dircolors)
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}

bindkey '^_' undo # ctrl + _ : undo last tab completion
bindkey -v # vi mode
bindkey '^r' history-incremental-search-backward

# cat -v + type in home, end to confirm escape sequencces
bindkey  "^[[H"   beginning-of-line # home
bindkey  "^[[F"   end-of-line       # end

# escape sequences when I run tmux
bindkey  "^[OH"   beginning-of-line # home
bindkey  "^[OF"   end-of-line       # end

if has_cmd direnv; then
  eval "$(direnv hook zsh)"
fi

# ctrl-r fzf
if [[ -e "${HOME}/.nix-profile/share/fzf" ]]; then
  source "${HOME}/.nix-profile/share/fzf/key-bindings.zsh"
fi
