theme = "monokai_custom"

[editor]
true-color = true
line-number = "relative"
cursorline = true

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal]
A-d = "delete_selection"
d = "delete_selection_noyank"
D = "@xd"
