#!/bin/bash

alias vim="$VIM_BIN"

if has_cmd dircolors; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

if has_cmd zsh; then
    alias tmux='SHELL=$(which zsh) tmux'
fi

if has_cmd git; then
    alias g='git'
    alias ga='git add'
    alias gc='git commit'
    alias gl='git log'
    alias gs='git status'
fi
