#!/bin/bash

function list-apt-manual() {
    # Subtract initially installed packages from everything marked as "manually" installed
    comm -23 <(apt-mark showmanual | sort -u) <(gzip -dc /var/log/installer/initial-status.gz | sed -n 's/^Package: //p' | sort -u)
}

function list-apt-repos() {
    (echo /etc/apt/sources.list && find /etc/apt/sources.list.d/ -regex '.*list') | xargs egrep -v '^#|^ *$'
}

function millis() {
    date +%s%N | cut -b1-13
}

function date_epoch() {
    # Good until Mar. 2255
    limit=9000000000
    ts=$1
    if (( $ts < $limit )); then
        date -d @${ts}
    elif (( $ts < $limit * 1000 )); then
        date -d @$(($ts / 1000))
    else
        date -d @$(($ts / 1000000))
    fi
}

function pcsv() {
    column -t -s, -n "$@" | less -S
}

function grepcode() {
    search=$1
    target=${2:-.}
    grep -r --include \*.py --include \*.c --include \*.rs --include \*.sh $search $target
}

if has_cmd fzf; then
    if has_cmd rg; then
        function fz() {
            target=$1
            if [[ "$2" == "--ignore" ]]; then
                # rg --files respects .gitignore files
                $target $(FZF_DEFAULT_COMMAND="rg --files" fzf)
            else
                $target $(fzf)
            fi
        }
    else
        function fz() {
            target=$1
            $target $(fzf)
        }
    fi

    function lfz() {
        fz less
    }

    function vfz() {
        fz $VIM_BIN
    }

    function lfzi() {
        fz less --ignore
    }

    function vfzi() {
        fz $VIM_BIN --ignore
    }
fi
