#!/bin/bash

alias vim="$VIM_BIN"

if has_cmd dircolors; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias grep='grep --color=auto'
fi

if has_cmd zsh; then
    alias tmux='SHELL=$(which zsh) tmux'
fi

if has_cmd git; then
    alias gl='git log'
    alias gs='git status'
    alias ga='git add -A'
    alias gc='git commit'
    alias gp='git push'
    alias gacp='git add -A && git commit -m "auto" && git push'
fi
