#!/bin/bash

function list-apt-manual() {
    # Subtract initially installed packages from everything marked as "manually" installed
    comm -23 <(apt-mark showmanual | sort -u) <(gzip -dc /var/log/installer/initial-status.gz | sed -n 's/^Package: //p' | sort -u)
}

function list-apt-repos() {
    (echo /etc/apt/sources.list && find /etc/apt/sources.list.d/ -regex '.*list') | xargs egrep -v '^#|^ *$'
}

function date_epoch() {
    # Good until Mar. 2255
    limit=9000000000
    ts=$1
    if (( $ts < $limit )); then
        date -d @${ts} --utc +"%Y/%m/%d %T %Z"
    elif (( $ts < $limit * 1000 )); then
        printf -v millis "%03d" $((ts % 1000))
        date -d @$(($ts / 1000)).$millis --utc +"%Y/%m/%d %T.%3N %Z"
    else
        printf -v micros "%06d" $((ts % 1000000))
        date -d @$(($ts / 1000000)).micros --utc +"%Y/%m/%d %T.%6N %Z"
    fi
}

function pcsv() {
    column -t -s, "$@" | less -S
}

function fz() {
    target=$1
    if [[ "$2" == "--ignore" ]]; then
        # rg --files respects .gitignore files
        $target $(FZF_DEFAULT_COMMAND="rg --files" fzf)
    else
        $target $(fzf)
    fi
}

function vfz() {
    fz $VIM_BIN --ignore
}

function replace() {
    rg --files-with-matches "${1}" ${3} | xargs -I {} sed --quiet "s/${1}/${2}/g" {}
    rg --files-with-matches "${1}" ${3} | xargs -I {} sed -r -i "s/${1}/${2}/g" {}
}
