#!/bin/bash

# Setup standard interactive shell environment for bash or zsh
# contains non shell-specific setup
# Compatible with bash and zsh

function has_cmd() {
    [[ -x "$(command -v $1)" ]]
}

if has_cmd nvim; then
    export VIM_BIN=nvim
else
    export VIM_BIN=vim
fi

export VISUAL="$VIM_BIN"
export EDITOR="$VISUAL"
export EMAIL="davidzeng.42@gmail.com"

# History File Settings
HISTSIZE=10000
HISTFILESIZE=10000

export XDG_CACHE_HOME="$HOME/.cache"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"

export LOCALE_ARCHIVE=/usr/lib/locale/locale-archive # something weird with nix + perl

export LESSHISTFILE=- # disable .lesshst
export PYTHONSTARTUP="$XDG_CONFIG_HOME/python/pythonrc"

BASH_CONFIG_HOME="$XDG_CONFIG_HOME/bash"

if [[ -f "$BASH_CONFIG_HOME/bash_functions" ]]; then
    . "$BASH_CONFIG_HOME/bash_functions"
fi

# Aliases can depend on functions
if [[ -f "$BASH_CONFIG_HOME/bash_aliases" ]]; then
    . "$BASH_CONFIG_HOME/bash_aliases"
fi

# Miscellaneous aliases, functions, etc. not worth preserving or generalizing beyond the current system
if [[ -f "$BASH_CONFIG_HOME/bash_local" ]]; then
    . "$BASH_CONFIG_HOME/bash_local"
fi

export PATH="/home/davidz/.avm/bin":$PATH
