#!/bin/bash

alias vim="$VIM_BIN"

if has_cmd python3; then
    if ! has_cmd python || [[ "$(python --version)" =~ "Python 2.*" ]]; then
        alias python='python3'
        alias pip='pip3'
    fi
fi

alias venv='virtualenv'
alias venva='source venv/bin/activate'

alias wget-agent='wget --user-agent="Mozilla/5.0"' # Get around 403 forbidden with wget

if has_cmd zsh; then
    alias tmux='SHELL=$(which zsh) tmux'
fi
