#!/bin/bash

function list-apt-manual() {
    # Subtract initially installed packages from everything marked as "manually" installed
    comm -23 <(apt-mark showmanual | sort -u) <(gzip -dc /var/log/installer/initial-status.gz | sed -n 's/^Package: //p' | sort -u)
}

function list-apt-repos() {
    (echo /etc/apt/sources.list && find /etc/apt/sources.list.d/ -regex '.*list') | xargs egrep -v '^#|^ *$'
}

function millis() {
    date +%s%N | cut -b1-13
}

function date_epoch() {
    # Good until Mar. 2255
    limit=9000000000
    ts=$1
    if (( $ts < $limit )); then
        date -d @${ts} --utc +"%Y/%m/%d %T %Z"
    elif (( $ts < $limit * 1000 )); then
        date -d @$(($ts / 1000)).$(($ts % 1000)) --utc +"%Y/%m/%d %T.%3N %Z"
    else
        date -d @$(($ts / 1000000)).$(($ts % 1000000)) --utc +"%Y/%m/%d %T.%6N %Z"
    fi
}

function pcsv() {
    column -t -s, -n "$@" | less -S
}

function vcsv() {
    column -t -s, -n "$@" | \
    vim - -R -u NONE -N +'map <right> 30zl
                        map <left> 30zh
                        map <C-d> 30jzz
                        map <C-u> 30kzz
                        map q :qa<CR>
                        set number scrollopt=hor scrollbind nowrap cursorline
                        1sp
                        winc w
                        '
}

function fz() {
    target=$1
    if [[ "$2" == "--ignore" ]]; then
        # rg --files respects .gitignore files
        $target $(FZF_DEFAULT_COMMAND="rg --files" fzf)
    else
        $target $(fzf)
    fi
}

function lfz() {
    fz less --ignore
}

function vfz() {
    fz $VIM_BIN --ignore
}

function lfza() {
    fz less
}

function vfza() {
    fz $VIM_BIN
}

function replace() {
    rg --files-with-matches ${1} ${3} | xargs -I {} sed -i "s/${1}/${2}/g" {}
}
